import { apiRequest } from '@/api/apiClient';
import { API_ENDPOINTS } from '@/config/api';

export type CustomerStatus = 'active' | 'inactive' | 'blocked';

export interface Customer {
  _id: string;
  phoneNumber: string;
  email?: string;
  name?: string;
  phoneVerified: boolean;
  phoneVerifiedAt?: string;
  onboardingCompleted: boolean;
  lastLogin?: string;
  loginCount: number;
  status: CustomerStatus;
  createdAt: string;
  updatedAt: string;
}

export interface CustomerListResponse {
  customers: Customer[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface CustomerStats {
  total: number;
  active: number;
  inactive: number;
  blocked: number;
  newToday: number;
  newThisWeek: number;
}

export interface CustomerListParams {
  page?: number;
  limit?: number;
  search?: string;
  status?: CustomerStatus;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export const fetchCustomers = async (params: CustomerListParams = {}): Promise<CustomerListResponse> => {
  const queryParams = new URLSearchParams();
  if (params.page) queryParams.append('page', String(params.page));
  if (params.limit) queryParams.append('limit', String(params.limit));
  if (params.search) queryParams.append('search', params.search);
  if (params.status) queryParams.append('status', params.status);
  if (params.sortBy) queryParams.append('sortBy', params.sortBy);
  if (params.sortOrder) queryParams.append('sortOrder', params.sortOrder);

  const qs = queryParams.toString();
  const endpoint = `${API_ENDPOINTS.admin.customers.list}${qs ? `?${qs}` : ''}`;
  const response = await apiRequest<{ success: boolean; data: CustomerListResponse }>(endpoint);
  return response.data;
};

export const fetchCustomerStats = async (): Promise<CustomerStats> => {
  const response = await apiRequest<{ success: boolean; data: CustomerStats }>(
    API_ENDPOINTS.admin.customers.stats
  );
  return response.data;
};

export const fetchCustomerById = async (id: string): Promise<Customer> => {
  const response = await apiRequest<{ success: boolean; data: Customer }>(
    API_ENDPOINTS.admin.customers.getById(id)
  );
  return response.data;
};

export const updateCustomer = async (id: string, data: { status: CustomerStatus }): Promise<Customer> => {
  const response = await apiRequest<{ success: boolean; data: Customer }>(
    API_ENDPOINTS.admin.customers.update(id),
    {
      method: 'PATCH',
      body: JSON.stringify(data),
    }
  );
  return response.data;
};

export interface CustomerAddress {
  _id: string;
  userId: string;
  label: string;
  line1: string;
  line2?: string;
  city: string;
  state?: string;
  pincode?: string;
  latitude?: number;
  longitude?: number;
  isDefault: boolean;
  order: number;
  createdAt: string;
  updatedAt: string;
}

export interface CustomerPaymentMethod {
  _id: string;
  userId: string;
  type: 'card' | 'upi' | 'wallet';
  last4: string;
  brand: string;
  cardholderName: string;
  upiId: string;
  walletName: string;
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
}

export const fetchCustomerAddresses = async (id: string): Promise<{ addresses: CustomerAddress[]; total: number }> => {
  const response = await apiRequest<{ success: boolean; data: { addresses: CustomerAddress[]; total: number } }>(
    API_ENDPOINTS.admin.customers.addresses(id)
  );
  return response.data;
};

export const fetchCustomerPaymentMethods = async (id: string): Promise<{ paymentMethods: CustomerPaymentMethod[]; total: number }> => {
  const response = await apiRequest<{ success: boolean; data: { paymentMethods: CustomerPaymentMethod[]; total: number } }>(
    API_ENDPOINTS.admin.customers.paymentMethods(id)
  );
  return response.data;
};

export interface PasswordInfo {
  hasPassword: boolean;
  isAutoGenerated: boolean;
  autoGeneratedPassword: string | null;
  passwordLastChangedAt: string | null;
  passwordLastChangedBy: 'system' | 'user' | 'admin' | null;
}

export const fetchPasswordInfo = async (id: string): Promise<PasswordInfo> => {
  const response = await apiRequest<{ success: boolean; data: PasswordInfo }>(
    API_ENDPOINTS.admin.customers.passwordInfo(id)
  );
  return response.data;
};

export const resetCustomerPassword = async (id: string): Promise<{ newPassword: string; message: string }> => {
  const response = await apiRequest<{ success: boolean; data: { newPassword: string; message: string } }>(
    API_ENDPOINTS.admin.customers.resetPassword(id),
    { method: 'PUT' }
  );
  return response.data;
};

export const setCustomerPassword = async (id: string, password: string): Promise<{ message: string }> => {
  const response = await apiRequest<{ success: boolean; data: { message: string } }>(
    API_ENDPOINTS.admin.customers.setPassword(id),
    {
      method: 'PUT',
      body: JSON.stringify({ password }),
    }
  );
  return response.data;
};
